# Generated by Django 6.1 on 2026-09-23 16:09

import textapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Επωνυμία')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=150, verbose_name='Θέμα')),
                ('message', models.TextField(verbose_name='Μήνυμα')),
                ('country', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Χώρα')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Πόλη')),
                ('language', models.CharField(blank=True, db_index=True, max_length=5, verbose_name='Γλώσσα')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Συσκευή')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Προέλευση')),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM campaign')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Συγκατάθεση')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ημερομηνία')),
            ],
            options={
                'verbose_name': 'Μήνυμα επικοινωνίας',
                'verbose_name_plural': 'Μηνύματα επικοινωνίας',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Κωδικός')),
                ('slug', models.SlugField(help_text='Μπαίνει στο URL, π.χ. ouranos-pike', max_length=60, unique=True, verbose_name='Slug')),
                ('name_el', models.CharField(max_length=120, verbose_name='Όνομα (ΕΛ)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Όνομα (ΕΝ)')),
                ('subtitle_el', models.CharField(blank=True, help_text='π.χ. Ουρανού, Cotton', max_length=120, verbose_name='Υπότιτλος (ΕΛ)')),
                ('subtitle_en', models.CharField(blank=True, max_length=120, verbose_name='Υπότιτλος (ΕΝ)')),
                ('short_el', models.TextField(blank=True, help_text='Εμφανίζεται στις κάρτες της αρχικής', verbose_name='Σύντομο κείμενο (ΕΛ)')),
                ('short_en', models.TextField(blank=True, verbose_name='Σύντομο κείμενο (ΕΝ)')),
                ('description_el', models.TextField(blank=True, verbose_name='Αναλυτικό κείμενο (ΕΛ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Αναλυτικό κείμενο (ΕΝ)')),
                ('description2_el', models.TextField(blank=True, verbose_name='Αναλυτικό κείμενο B (ΕΛ)')),
                ('description2_en', models.TextField(blank=True, verbose_name='Αναλυτικό κείμενο B (ΕΝ)')),
                ('description3_el', models.TextField(blank=True, verbose_name='Αναλυτικό κείμενο C (ΕΛ)')),
                ('description3_en', models.TextField(blank=True, verbose_name='Αναλυτικό κείμενο C (ΕΝ)')),
                ('description4_el', models.TextField(blank=True, verbose_name='Αναλυτικό κείμενο D (ΕΛ)')),
                ('description4_en', models.TextField(blank=True, verbose_name='Αναλυτικό κείμενο D (ΕΝ)')),
                ('composition_el', models.CharField(blank=True, help_text='π.χ. 100% πολυεστερικό νήμα', max_length=150, verbose_name='Σύνθεση (ΕΛ)')),
                ('composition_en', models.CharField(blank=True, max_length=150, verbose_name='Σύνθεση (ΕΝ)')),
                ('weight', models.CharField(blank=True, help_text='π.χ. 280 g/m²', max_length=60, verbose_name='Βάρος')),
                ('density', models.CharField(blank=True, max_length=60, verbose_name='Πυκνότητα')),
                ('thickness', models.CharField(blank=True, help_text='π.χ. 0,9 mm', max_length=60, verbose_name='Πάχος υλικού')),
                ('foam', models.CharField(blank=True, help_text='π.χ. 35kg - standard 0,6 mm (0,2-0,8 mm)', max_length=80, verbose_name='Αφρολέξ')),
                ('color_el', models.CharField(blank=True, max_length=150, verbose_name='Χρώματα (ΕΛ)')),
                ('color_en', models.CharField(blank=True, max_length=150, verbose_name='Χρώματα (ΕΝ)')),
                ('pattern_el', models.CharField(blank=True, max_length=150, verbose_name='Σχέδιο (ΕΛ)')),
                ('pattern_en', models.CharField(blank=True, max_length=150, verbose_name='Σχέδιο (ΕΝ)')),
                ('bielasticity', models.BooleanField(default=False, help_text='Εμφανίζει το icon bielasticity', verbose_name='Διελαστικότητα')),
                ('image_main', models.ImageField(blank=True, upload_to='products/', verbose_name='Κύρια φωτό')),
                ('image_2', models.ImageField(blank=True, upload_to='products/', verbose_name='Φωτό 2')),
                ('image_3', models.ImageField(blank=True, upload_to='products/', verbose_name='Φωτό 3')),
                ('image_4', models.ImageField(blank=True, upload_to='products/', verbose_name='Φωτό 4')),
                ('image_5', models.ImageField(blank=True, upload_to='products/', verbose_name='Φωτό 5')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Σειρά')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Προϊόν',
                'verbose_name_plural': 'Προϊόντα',
                'ordering': ['order', 'code'],
            },
            bases=(textapp.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('language', models.CharField(blank=True, max_length=5, verbose_name='Γλώσσα')),
                ('source', models.CharField(choices=[('footer', 'Footer'), ('contact', 'Φόρμα επικοινωνίας'), ('other', 'Άλλο')], default='footer', max_length=20, verbose_name='Προέλευση')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Επιβεβαιώθηκε')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Απεγγράφηκε')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ημερομηνία')),
            ],
            options={
                'verbose_name': 'Συνδρομητής',
                'verbose_name_plural': 'Συνδρομητές',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'Προϊόν'), ('swatch', 'Δείγμα')], db_index=True, max_length=10, verbose_name='Είδος')),
                ('item', models.CharField(db_index=True, help_text="π.χ. 'ouranos-pike' ή 'K622'", max_length=120, verbose_name='Κωδικός')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Session')),
                ('language', models.CharField(blank=True, max_length=5, verbose_name='Γλώσσα')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ημερομηνία')),
            ],
            options={
                'verbose_name': 'Προβολή',
                'verbose_name_plural': 'Προβολές',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'item', 'created_at'], name='textapp_ite_kind_39b72b_idx')],
            },
        ),
    ]
