# Generated by Django 6.1 on 2026-09-24 13:04

import django.db.models.deletion
import textapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Μπαίνει στο URL, π.χ. pike-ouranou', max_length=60, unique=True, verbose_name='Slug')),
                ('name_el', models.CharField(max_length=120, verbose_name='Όνομα (ΕΛ)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Όνομα (ΕΝ)')),
                ('subtitle_el', models.CharField(blank=True, max_length=120, verbose_name='Υπότιτλος (ΕΛ)')),
                ('subtitle_en', models.CharField(blank=True, max_length=120, verbose_name='Υπότιτλος (ΕΝ)')),
                ('short_el', models.TextField(blank=True, help_text='Εμφανίζεται στην κάρτα του είδους', verbose_name='Σύντομο κείμενο (ΕΛ)')),
                ('short_en', models.TextField(blank=True, verbose_name='Σύντομο κείμενο (ΕΝ)')),
                ('intro_el', models.TextField(blank=True, help_text='Η παρουσίαση στην κορυφή της σελίδας', verbose_name='Γενικό κείμενο (ΕΛ)')),
                ('intro_en', models.TextField(blank=True, verbose_name='Γενικό κείμενο (ΕΝ)')),
                ('intro2_el', models.TextField(blank=True, verbose_name='Γενικό κείμενο B (ΕΛ)')),
                ('intro2_en', models.TextField(blank=True, verbose_name='Γενικό κείμενο B (ΕΝ)')),
                ('meta_description_el', models.CharField(blank=True, max_length=160, verbose_name='Meta description (ΕΛ)')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, verbose_name='Meta description (ΕΝ)')),
                ('image_main', models.ImageField(blank=True, upload_to='categories/', verbose_name='Κύρια φωτό')),
                ('image_2', models.ImageField(blank=True, upload_to='categories/', verbose_name='Φωτό 2')),
                ('image_3', models.ImageField(blank=True, upload_to='categories/', verbose_name='Φωτό 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Σειρά')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Είδος',
                'verbose_name_plural': 'Είδη',
                'ordering': ['order', 'name_el'],
            },
            bases=(textapp.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_el',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta description (ΕΛ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta description (ΕΝ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='textapp.category', verbose_name='Είδος'),
            preserve_default=False,
        ),
    ]
