# Generated by Django 6.1 on 2026-09-26 11:51

import textapp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0002_category_product_meta_description_el_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name_el'], 'verbose_name': 'Κατηγορία', 'verbose_name_plural': 'Κατηγορίες'},
        ),
        migrations.AddField(
            model_name='category',
            name='image_10',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Φωτό 10'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_4',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Φωτό 4'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_5',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Φωτό 5'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_6',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Φωτό 6'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_7',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Φωτό 7'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_8',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Φωτό 8'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_9',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Φωτό 9'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_2',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Φωτό 2'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_3',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Φωτό 3'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_main',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='categories/', verbose_name='Κύρια φωτό'),
        ),
        migrations.AlterField(
            model_name='itemview',
            name='kind',
            field=models.CharField(choices=[('category', 'Είδος'), ('product', 'Προϊόν'), ('swatch', 'Δείγμα')], db_index=True, max_length=10, verbose_name='Είδος'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='products/', verbose_name='Φωτό 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='products/', verbose_name='Φωτό 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='products/', verbose_name='Φωτό 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='products/', verbose_name='Φωτό 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_main',
            field=models.ImageField(blank=True, storage=textapp.storage.OverwriteStorage(), upload_to='products/', verbose_name='Κύρια φωτό'),
        ),
    ]
