# Generated by Django 6.1 on 2026-09-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0003_alter_category_options_category_image_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='intro3_el',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο C (ΕΛ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro3_en',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο C (ΕΝ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro4_el',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο D (ΕΛ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro4_en',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο D (ΕΝ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro5_el',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο E (ΕΛ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro5_en',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο E (ΕΝ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro6_el',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο F (ΕΛ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro6_en',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο F (ΕΝ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro7_el',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο G (ΕΛ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro7_en',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο G (ΕΝ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro8_el',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο H (ΕΛ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro8_en',
            field=models.TextField(blank=True, verbose_name='Γενικό κείμενο H (ΕΝ)'),
        ),
    ]
